import styles from './layout.module.css'

import { headers } from 'next/headers';
import { redirect } from 'next/navigation';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
export default function LayoutHome({ children }) {
    const currentUrl = headers().get("next-url");
    return (
        <div id = {styles.parrentDiv} className='w-screen h-screen p-5 grid-cols-2 gap-5'>
            <nav className='flex flex-col justify-between h-full border-2 rounded-lg p-5'>
                <div>
                    <ol className='flex flex-col gap-3'>
                        <li>Home</li>
                        <li>Tasks</li>
                        <li>Friend Name Tasks</li>
                    </ol>
                </div>
                <div className='flex gap-1 items-center'>
                    <span className='rounded-full bg-slate-400 aspect-square w-5 h-5'></span><span>Username</span>
                </div>
            </nav>
            <main className='w-full h-full rounded-lg'>
                <span className='text-[#767676] text-sm'>{currentUrl}</span>
                {children}
            </main>
        </div>
    );
}